CREATE DATABASE IF NOT EXISTS php_rush_mvc;
USE php_rush_mvc;

CREATE TABLE IF NOT EXISTS users
(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(255) UNIQUE NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
user_group ENUM('USER', 'WRITER', 'ADMIN') NOT NULL DEFAULT 'USER',
status BOOLEAN NOT NULL DEFAULT true,
creation_date DATETIME NOT NULL,
edition_date DATETIME NULL
);

CREATE TABLE IF NOT EXISTS categories
(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
parent_id BIGINT NULL,
FOREIGN KEY(parent_id) REFERENCES categories(id) 
);

CREATE TABLE IF NOT EXISTS articles
(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_writer BIGINT NOT NULL,
id_category BIGINT NOT NULL,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
path_image VARCHAR(255) NULL,
creation_date DATETIME NOT NULL,
edition_date DATETIME NULL,
FOREIGN KEY(id_writer) REFERENCES users(id),
FOREIGN KEY(id_category) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS comments
(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_writer BIGINT NOT NULL,
id_article BIGINT NOT NULL,
content TEXT NOT NULL,
creation_date DATETIME NOT NULL,
edition_date DATETIME NULL,
FOREIGN KEY(id_writer) REFERENCES users(id),
FOREIGN KEY(id_article) REFERENCES articles(id)
);

CREATE TABLE IF NOT EXISTS tags
(
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS articles_tags
(
id_article BIGINT NOT NULL,
id_tag BIGINT NOT NULL,
FOREIGN KEY(id_article) REFERENCES articles(id),
FOREIGN KEY(id_tag) REFERENCES tags(id)
);